services:
  redis:
    image: redis:7-alpine
    container_name: redis
    volumes:
      - redis-data:/data
    restart: unless-stopped

  authelia:
    image: authelia/authelia:4.38.10
    container_name: authelia
    volumes:
      - ./authelia/config:/config
    ports:
      - "9091:9091"
    depends_on:
      - redis
    environment:
      - AUTHELIA_STORAGE_ENCRYPTION_KEY=unsecure_storage_encryption_key_at_least_32_chars
      - AUTHELIA_SESSION_SECRET=unsecure_session_secret_at_least_32_chars_long
      - AUTHELIA_IDENTITY_PROVIDERS_OIDC_HMAC_SECRET=unsecure_hmac_secret_at_least_32_chars_long
    restart: unless-stopped


volumes:
  redis-data:
