[project]
name = "apps"
version = "0.1.0"
description = "Market Intelligence Chatbot Testboard"
requires-python = ">=3.13,<3.14"
readme = "README.md"
dependencies = [
    "adxp-cli>=0.1.12",
    "black>=25.1.0",
    "botocore>=1.38.15",
    "duckduckgo-search>=8.0.2",
    "fastapi>=0.115.12",
    "fastmcp>=2.3.3",
    "langchain-community>=0.3.24",
    "langchain-openai>=0.3.16",
    "langgraph>=0.4.3",
    "loguru>=0.7.3",
    "matplotlib>=3.10.3",
    "mcp>=1.8.1",
    "openai>=1.78.1",
    "openinference-instrumentation-langchain>=0.1.33",
    "arize-phoenix>=8.8.0",
    "arize-phoenix-otel>=0.8.0",
    "pydantic-ai>=0.2.3",
    "python-dotenv>=1.1.0",
    "tabulate>=0.9.0",
    "uvicorn>=0.30.6,<0.31.0",
    "scipy>=1.16.0",
    "langchain-core>=0.3.69",
    "tavily-python>=0.7.10",
    "pytest>=8.4.1",
    "pytest-env>=1.1.5",
    "exa-py>=1.14.18",
    "pydantic>=2.10.6",
    "pytest-asyncio>=1.1.0",
    "bs4>=0.0.2",
    "langchain-mcp-adapters>=0.1.9",
    "pandas>=2.3.2",
    "python-multipart>=0.0.9,<0.0.10",
    "uvloop>=0.17.0; sys_platform != 'win32'",
    "watchfiles>=0.18.0",
    "websockets>=10.4",
    "langgraph-supervisor>=0.0.29",
    "gunicorn>=23.0.0",
    "adxp-sdk>=0.1.12",
]

[tool.pytest.ini_options]
testpaths = ["test"]
pythonpath = [".", "mari_agent"]
env_files = [".env"]
addopts = "--tb=short --strict-markers -v -s --log-cli-level=INFO --asyncio-mode=auto"
asyncio_mode = "auto"

#[tool.uv]
#index-url="https://skpc-nexus.skpc.cloudzcp.net/repository/pypi-sre-proxy/simple"