###############################################################
#                   Authelia Configuration                    #
###############################################################

server:
  address: 'tcp://0.0.0.0:9091/'

log:
  level: info

totp:
  issuer: Authelia

authentication_backend:
  file:
    path: /config/users_database.yml

access_control:
  default_policy: deny
  rules:
    - domain: "*"
      policy: bypass

session:
  name: authelia_session
  same_site: lax
  secret: unsecure_session_secret_change_me_at_least_32_chars
  expiration: 1h
  inactivity: 5m
  cookies:
    - domain: '127.0.0.1'
      authelia_url: 'http://127.0.0.1:9091'
      default_redirection_url: 'http://127.0.0.1:8000'

storage:
  local:
    path: /config/db.sqlite3
  encryption_key: unsecure_storage_encryption_key_at_least_32_chars

notifier:
  filesystem:
    filename: /config/notification.txt

identity_validation:
  reset_password:
    jwt_secret: unsecure_reset_password_jwt_secret_at_least_32_chars

identity_providers:
  oidc:
    hmac_secret: unsecure_hmac_secret_change_me_at_least_32_chars
    jwks:
      - key: |
          -----BEGIN RSA PRIVATE KEY-----
          MIIEowIBAAKCAQEArsDEB+djRWuQ0hJZ678cd0e1jtFuxtEx3WQAP2IzuzAq/6qh
          ntO56/ggblfyvhZoFsYbDNHyuwNsue0snXNeVeetGRGY4IyJuawVvXsWNR9QVRDm
          7mdZCeDB1TBIi7a6FgfxF0mYUkGTPNphQVVnDg0tTRbRgsoOsr7mHLLKn5K10gD4
          P1Zhnf8ht3uumQpxhJfG+8ehN3+/GndhiRlI1Pmsj4lqU7XB/pdNVbN31Q/s+aaw
          Bn0uYnjozjtFxVbS0rEif5OIpcg72cnARgpatqnKc9fWuh+81hlHCjXjbpnQMOmH
          E4/xHTuZ7EQl7uJRtRVjGFP3aYxgED33Rmu7RwIDAQABAoIBAQCWH2tIDvMs89cZ
          YEJ3T1o47hV+d1Re39+ifQHpcYdXS23k7MSjGOgjWqkhodQakE0jI1Shksqe9bY1
          kxY8vJtR2RDO9FsMrC60nqyedlsBj8EHEtoP/CB1Z+ucJTptK7B4tKHci5CbOVIv
          eLsL0T4SyCcejne1j7dIvs4X4VBH++isBEwcALbbKGsOCWZmNbW5qAE19QSmxLyy
          /oUaEUA3XAj8DS/c0BAylFhxO3+Cts0kWoNvkd2odIKS6ETixjlbjmi63laeyfEz
          fzpYMJ/auTF2/PbgMn9fsZheFgpg/J02W1tWcNfK7YTaZbdw/5wrJyMpazAQxSoq
          AZPOZIThAoGBAOFXca+Zz1BLs4pbS9CK5/5FpcVbK3rH97RZC8JgIaCLRedIBQ+P
          pRhraY7G4nRz066DaJ7eWGlAWyH02y/U0kUxMaeqSnlkV6Kgq+XalxAUOYHL2ThW
          9ZRBvP61HICQPq5UVGK5cCPirvoySHg4w9XajuzUyxSRr/zKq/KdULx7AoGBAMaH
          V3agDJfOYQZxZHdGaJpH4tetIa02Nr4qerxZe6hSTdwyOhLzEF3mUJj5RdCf3YB9
          OnLRgceBYGxK1s0w1eins4PildNWm8JlE2L2NqIo07fgcKHtxXO0kUhswExD1T0F
          fEVbCGbBypemum3JE1jmwDxQPNWMOnsHiAZMMsClAoGAW24ee5Bd1IeSpn2ailgB
          /2KE+0mdn6jJMYy7v7c/jaNUzp2jKAgxhXH3l23M7lEcv38kEOnIV5Q8Jc/yqzqf
          wmFOc2gd5Zk4EY09kfqaNnTuTGLIlRp7dBckNviHQwbD1/nxb0ksXfMY6f1C+DyY
          AQo32ZIRgBwImvokwEDiREcCgYBZDFP67Yc4gGWc0jfSGE7LBPuG6i102CBt4/fx
          i+GfemtaHV1XKpdoxunX89eQ4GQmQgV5gufHaQyrBlaa6xDHrpEi0vuJNAvhghzU
          AsQ2sEFm9NEQkOpEH/Yamk0W6EY5fMBlC5QVI0+P/kUZAVwgQEBxzTu8PY3tqU8m
          I/+P0QKBgDmpW9BS6MBgAbKh02DKwZjVr7K1k/aReSE0RsYtnkNEarjFvhZvSA5F
          KsX/SsGjAzoF8roLwu7yEV/R0QgGYdlq2JnOybshfx1gdXbrpB0r/dMljMaU/Wz4
          K5HgtG5SugrWLgfgNn8dobQkA4ztpEDfKvkw4otWXAKxPYr+4PZP
          -----END RSA PRIVATE KEY-----
    clients:
      - client_id: fastlangframe
        client_name: FastLangFrame
        # client_secret is 'fastlangframe_secret'
        client_secret: '$pbkdf2-sha512$310000$c2FsdHNhbHQ$8mR9YV/6NlY6m5Y8kP9z8n8p8u3K2h8e8u9z8n8p8u3K2h8e8u9z8n8p8u3K2h8e8u9z8n8p8u3K2h8'
        public: false
        authorization_policy: one_factor
        redirect_uris:
          - http://127.0.0.1:8000/docs/oauth2-redirect
        scopes:
          - openid
          - profile
          - email
          - groups
        grant_types:
          - authorization_code
          - refresh_token
          - password
        userinfo_signed_response_alg: none
